<>
<div className='todo project'>

                <div>
                    <h3>ToDo App</h3>
                    <div className='project-brief'>
                        <p>Its a To-Do web application. You can add to-do items, delete them, and mark as complete by double
                            clicking on the item. And even you can re-arrange the items.</p>
                        <p>Tools Used:</p>
                        <ul>
                            <li>JS</li>
                            <li>JQuery</li>
                            <li>CSS</li>
                            <li>HTML</li>
                        </ul>

                        <div className='project-btn'>
                            <div><a target="_blank" rel="noopener noreferrer" href='https://github.com/Priyanka-koraganji/to-do-list-app'>Github Repo</a></div>
                            {/* <div><a target="_blank" rel="noopener noreferrer" href='https://priyanka-koraganji.github.io/to-do-list-app/'>Visit Site</a></div> */}
                        </div>
                    </div>

                </div>
                <div className='project-images'>
                    <img className='todo-proj-img' src={Todo} width="100%" alt=""></img>
                </div>
            </div>

<div className='notes-app project'>

<div>
    <h3>Notes App</h3>
    <div className='project-brief'>
        <p>Its a Notes app. We can add a note which is like a sticker, and can even edit and delete the note. User can add any number of notes, edit or delete them. Also we can save the notes to local storage.</p>
        <p>Tools Used:</p>
        <ul>
            <li>JS</li>
            <li>CSS</li>
            <li>HTML</li>
        </ul>

        <div className='project-btn'>
            <div><a target="_blank" rel="noopener noreferrer" href='https://github.com/Priyanka-koraganji/to-do-list-app'>Github Repo</a></div>
            {/* <div><a target="_blank" rel="noopener noreferrer" href='https://priyanka-koraganji.github.io/to-do-list-app/'>Visit Site</a></div> */}
        </div>
    </div>

</div>
<div className='project-images'>
    <img className='todo-proj-img' src={Notes} width="100%" alt=""></img>
</div>
</div>


<div className='get-quote project'>

                <div>
                    <h3>Get Quote</h3>
                    <div className='project-brief'>
                        <p>Its an app, where you get random quotes. The quotes are to keep you motivated. These are generated by using an API.</p>
                        <p>Tools Used:</p>
                        <ul>
                            <li>JS</li>
                            <li>CSS</li>
                            <li>HTML</li>
                        </ul>

                        <div className='project-btn'>
                            <div><a target="_blank" rel="noopener noreferrer" href='https://github.com/Priyanka-koraganji/get-github-profiles'>Github Repo</a></div>
                            {/* <div><a target="_blank" rel="noopener noreferrer" href='https://priyanka-koraganji.github.io/to-do-list-app/'>Visit Site</a></div> */}
                        </div>
                    </div>

                </div>
                <div className='project-images'>
                    <img className='todo-proj-img' src={GetQuote} width="100%" alt=""></img>
                </div>
            </div>


            <div className='my-water project'>

<div>
    <h3>My Water Intake</h3>
    <div className='project-brief'>
        <p>Its a app to track water intake. It just adds 250ml water by selecting each glass which adds up to 2000ml in total. This is mainly helpful for the one who want to track the water intake.</p>
        <p>Tools Used:</p>
        <ul>
            <li>JS</li>
            <li>CSS</li>
            <li>HTML</li>
        </ul>

        <div className='project-btn'>
            <div><a target="_blank" rel="noopener noreferrer" href='https://github.com/Priyanka-koraganji/my-water'>Github Repo</a></div>
            {/* <div><a target="_blank" rel="noopener noreferrer" href='https://priyanka-koraganji.github.io/to-do-list-app/'>Visit Site</a></div> */}
        </div>
    </div>

</div>
<div className='project-images'>
    <img className='todo-proj-img' src={Water} width="100%" alt=""></img>
</div>
</div>


<div className='get-github-profiles project'>

                <div>
                    <h3>Get Github Profiles</h3>
                    <div className='project-brief'>
                        <p>Its an app that displays Github profile details of the users. When you enter the github user name, it displays the user details using Github API. Also it displays user latest repositories.</p>
                        <p>Tools Used:</p>
                        <ul>
                            <li>JS</li>
                            <li>CSS</li>
                            <li>HTML</li>
                        </ul>

                        <div className='project-btn'>
                            <div><a target="_blank" rel="noopener noreferrer" href='https://github.com/Priyanka-koraganji/get-github-profiles'>Github Repo</a></div>
                            {/* <div><a target="_blank" rel="noopener noreferrer" href='https://priyanka-koraganji.github.io/to-do-list-app/'>Visit Site</a></div> */}
                        </div>
                    </div>

                </div>
                <div className='project-images'>
                    <img className='todo-proj-img' src={GetGithub} width="100%" alt=""></img>
                </div>
            </div>

            


</>